name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2


      - name: Install Dependencies
        run: |
          sudo apt install -y libglfw3-dev libglm-dev

      - name: Build Network
        run: |
          cp -rf src net/copy
          cd net
          make clean
          make -j16

      - name: Build App
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..
          make -j8
 
        
